version: 0.2

phases:
  pre_build:
    commands:

      - CHANGED=$(git diff --name-only HEAD~1 HEAD)
      - "$CHANGED"
      - |
        if echo "$CHANGED" | grep -q "src/LS.Gateway/"; then 
          echo "Change detected in gateway api"
        else
          echo "No change detected - skipping"
          exit 0
        fi

      - echo "Logging into ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_DEFAULT_REGION=us-east-2

      # ECR Repo
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/lsf-dev-gateway-api-repo
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)

      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo "Building Gateway API Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG -f $DOCKERFILE_PATH .

      #- docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:

      - sed -i "s|<TASK_EXECUTION_ROLE_ARN>|$TASK_EXECUTION_ROLE_ARN|g" deploy/gateway-api/taskdef.json
      - sed -i "s|<TASK_ROLE_ARN>|$TASK_ROLE_ARN|g" deploy/gateway-api/taskdef.json
      - sed -i "s|<SQLSERVER_SECRET_ARN>|$SQLSERVER_SECRET_ARN|g" deploy/gateway-api/taskdef.json
      - echo "Generated taskdef:"
      - cat deploy/gateway-api/taskdef.json

      - echo "Pushing Docker images..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      #- docker push $REPOSITORY_URI:latest

      # IMPORTANT: required by CodeDeploy ECS Blue/Green
      - echo "Creating imageDetail.json..."
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

      - echo "Build completed successfully."

artifacts:
  name: build_output
  files:
    #- taskdef.json
    #- appspec.yaml
    - imageDetail.json
    #- deploy/gateway-api/imageDetail.json
    - deploy/gateway-api/taskdef.json
    - deploy/gateway-api/appspec.yaml