name: Doctor API

on:
  push:
    branches:
      - main
    paths:
      - 'src/LS.DoctorApi/**'
      - 'deploy/doctor-api/**'

jobs:

  # BUILD AND DEPLOY (CD)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Doctor API
        run: |
          aws codepipeline start-pipeline-execution \
            --name doctor-api-pipeline