name: Frontend

on:
  push:
    branches: [main]
    paths:
      - 'deploy/ls-front-end/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Frontend
        run: |
          aws codepipeline start-pipeline-execution \
            --name ls-framework-frontend-pipeline