name: Notification API

on:
  push:
    branches:
      - main
    paths:
      - 'src/LS.NotificationApi/**'
      - 'deploy/notification-api/**'

jobs:

  # BUILD AND DEPLOY (CD)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Notification API
        run: |
          aws codepipeline start-pipeline-execution \
            --name notification-api-pipeline