name: Billing API

on:
  push:
    branches:
      - main
    paths:
      - 'src/LS.BillingApi/**'
      - 'deploy/billing-api/**'

jobs:

  # BUILD AND DEPLOY (CD)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Billing API
        run: |
          aws codepipeline start-pipeline-execution \
            --name billing-api-pipeline