name: Worker Service

on:
  push:
    branches:
      - main
    paths:
      - 'src/LS.WorkerService/**'
      - 'deploy/worker-service/**'

jobs:

  # BUILD AND DEPLOY (CD)
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Worker Service
        run: |
          aws codepipeline start-pipeline-execution \
            --name worker-service-pipeline